//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelephoneSet
    {
        public int IdTelephone { get; set; }
        public string NumeroTel { get; set; }
        public string TypeNumero { get; set; }
        public int client_nclient { get; set; }
    }
}
